/* ============================================================
   WILD CONNECTIONS — Mock User Database
   Rich profiles with all registration form fields
   for matching algorithm demo
   ============================================================ */

const mentors = [
  {
    id: 1,
    name: "Valentina Tanono",
    specialty: "Escalamiento Financiero",
    image: "assets/mentor-valentina.jpg",
    bio: "Mentora en Escalamiento Financiero con 10+ años de experiencia. Ayuda a emprendedoras a estructurar sus finanzas para crecer sostenidamente.",
    // ─ Registration form fields ─
    location: "Miami, USA",
    instagram: "@valentina.tanono",
    businessStage: "scaling",
    monthlyRevenue: "15000_plus",
    businessYears: "5_plus",
    deliveryModel: ["service_1on1", "group_programs"],
    teamSize: "small_2_4",
    challenge90Days: "Quiero lanzar un programa grupal de alto ticket que escale sin depender de mi tiempo 1 a 1.",
    painPoints: ["revenue_ceiling", "cant_delegate"],
    niche: "Finanzas para emprendedoras",
    expertise: "Escalamiento financiero y modelos de negocio rentables",
    targetAudience: ["women_starting", "independent_pros"],
    idealClient: "Emprendedora que ya factura $3k+/mes y quiere escalar a $10k sin quemarse.",
    mainOfferPrice: "3000_plus",
    needsToHire: ["copywriting", "ads"],
    microphonePitch: "Busco una copywriter que entienda finanzas y una experta en Meta Ads para escalar mi funnel.",
    hobbies: ["exercise", "travel", "read"],
    socialEnergy: "super_social",
    humanDesign: "Generadora Manifestante 3/5",
    myPersonCriteria: "Alguien que hable de números sin miedo, que ya haya roto el techo de ingresos y que le guste reírse mientras trabaja.",
    nextObjective: "Facturar $50k/mes con mi programa grupal",
    threeYearVision: "Tener una escuela de finanzas para mujeres con presencia en toda Latinoamérica.",
    eventExpectation: "Encontrar alianzas estratégicas y posibles co-speakers.",
    purchaseReason: ["speakers", "networking", "money_talk"],
    tags: ["Finanzas", "Escalamiento", "Alto Ticket"]
  },
  {
    id: 2,
    name: "Carolina Méndez",
    specialty: "Marketing Digital",
    image: "assets/mentor-carolina.jpg",
    bio: "Especialista en Growth Marketing. Conecta estrategias de ventas digitales con el bienestar personal para un emprendimiento equilibrado.",
    location: "Bogotá, Colombia",
    instagram: "@carolinamendez.mkt",
    businessStage: "stable_income",
    monthlyRevenue: "6000_15000",
    businessYears: "3_5",
    deliveryModel: ["service_1on1", "digital_product"],
    teamSize: "freelancers",
    challenge90Days: "Necesito sistematizar mis procesos de venta para no depender de lanzamientos cada 3 meses.",
    painPoints: ["no_strategy", "cant_delegate"],
    niche: "Marketing digital para marcas de bienestar",
    expertise: "Estrategia de contenido, embudos de venta y lanzamientos",
    targetAudience: ["women_starting", "established_brands"],
    idealClient: "Marca de bienestar o belleza que quiere crecer en redes sociales de forma orgánica y con paid ads.",
    mainOfferPrice: "1500_3000",
    needsToHire: ["web_design", "photography"],
    microphonePitch: "Busco una diseñadora web que entienda conversión y una fotógrafa para mi marca personal.",
    hobbies: ["meditation", "cook", "travel"],
    socialEnergy: "small_groups",
    humanDesign: "Proyectora 4/6",
    myPersonCriteria: "Alguien estratégica pero con alma. Que hable de dinero con naturalidad y también le guste desconectar.",
    nextObjective: "Lanzar mi membresía y facturar $15k/mes consistentemente",
    threeYearVision: "Tener mi agencia boutique de marketing para marcas conscientes, con un equipo de 8 personas.",
    eventExpectation: "Conocer emprendedoras que necesiten marketing y posibles colaboraciones.",
    purchaseReason: ["networking", "community", "visibility"],
    tags: ["Marketing", "Contenido", "Lanzamientos"]
  },
  {
    id: 3,
    name: "Isabella Reyes",
    specialty: "Yoga y Bienestar",
    image: "assets/mentor-isabella.jpg",
    bio: "Coach de bienestar corporativo. Su enfoque en el mindfulness ayuda a líderes a mantener el balance mientras escalan sus negocios.",
    location: "Ciudad de México, México",
    instagram: "@isabellareyes.wellness",
    businessStage: "selling_irregular",
    monthlyRevenue: "1000_3000",
    businessYears: "1_3",
    deliveryModel: ["service_1on1", "group_programs", "content_creation"],
    teamSize: "solo",
    challenge90Days: "Necesito encontrar mi nicho específico y dejar de ofrecer de todo. Quiero un producto principal que venda solo.",
    painPoints: ["no_visibility", "no_strategy"],
    niche: "Bienestar y mindfulness para emprendedoras",
    expertise: "Yoga, meditación y coaching de bienestar integral",
    targetAudience: ["women_starting", "independent_pros"],
    idealClient: "Mujer emprendedora agotada que necesita reconectar con su energía para hacer crecer su negocio desde el equilibrio.",
    mainOfferPrice: "100_500",
    needsToHire: ["branding", "social_media", "web_design"],
    microphonePitch: "Busco una estratega de marca que me ayude a posicionarme como referente en bienestar para emprendedoras.",
    hobbies: ["meditation", "nature", "cook", "art"],
    socialEnergy: "observe_first",
    humanDesign: "Generadora 2/4",
    myPersonCriteria: "Alguien cálida, que ya tenga claridad en su negocio y que me inspire a dar el siguiente paso sin presión.",
    nextObjective: "Lanzar mi primer retiro presencial de bienestar para emprendedoras",
    threeYearVision: "Tener un centro de bienestar con retiros trimestrales y una comunidad online de 500 mujeres.",
    eventExpectation: "Inspiración, claridad y contactos para colaboraciones de bienestar.",
    purchaseReason: ["community", "networking", "speakers"],
    tags: ["Bienestar", "Yoga", "Mindfulness"]
  },
  {
    id: 4,
    name: "Sofía Navarro",
    specialty: "Consultoría de Negocios",
    image: "assets/mentor-sofia.jpg",
    bio: "Consultora de negocios. Su pasión es transformar ideas pequeñas en empresas altamente rentables a través de modelos financieros sólidos.",
    location: "Buenos Aires, Argentina",
    instagram: "@sofianavarro.biz",
    businessStage: "scaling",
    monthlyRevenue: "6000_15000",
    businessYears: "5_plus",
    deliveryModel: ["service_1on1", "group_programs"],
    teamSize: "small_2_4",
    challenge90Days: "Quiero automatizar mi onboarding de clientes y crear un sistema de referidos que funcione solo.",
    painPoints: ["cant_delegate", "revenue_ceiling"],
    niche: "Consultoría estratégica para negocios de servicio",
    expertise: "Modelos de negocio, pricing y operaciones",
    targetAudience: ["independent_pros", "established_brands"],
    idealClient: "Profesional independiente que factura $5k+ y quiere pasar de freelancer a CEO.",
    mainOfferPrice: "1500_3000",
    needsToHire: ["accounting", "legal"],
    microphonePitch: "Busco una contadora bilingüe para mi LLC y una abogada que entienda contratos internacionales.",
    hobbies: ["read", "travel", "exercise"],
    socialEnergy: "super_social",
    humanDesign: "Manifestadora 1/3",
    myPersonCriteria: "Alguien directa, sin rodeos, que piense en grande y no tenga miedo a cobrar lo que vale.",
    nextObjective: "Crear mi certificación para consultoras y escalar a $30k/mes",
    threeYearVision: "Liderar una firma de consultoría con presencia en 5 países de Latinoamérica.",
    eventExpectation: "Alianzas estratégicas y potenciales clientes de alto nivel.",
    purchaseReason: ["networking", "money_talk", "visibility"],
    tags: ["Consultoría", "Estrategia", "Operaciones"]
  },
  {
    id: 5,
    name: "Daniela Rojas",
    specialty: "Embudos de Venta",
    image: "assets/mentor-valentina.jpg",
    bio: "Experta en estrategias de embudos de venta y automatización de marketing para servicios de alto ticket.",
    location: "Medellín, Colombia",
    instagram: "@danielarojas.funnels",
    businessStage: "stable_income",
    monthlyRevenue: "3000_6000",
    businessYears: "3_5",
    deliveryModel: ["service_1on1", "digital_product"],
    teamSize: "freelancers",
    challenge90Days: "Quiero dejar de depender de lanzamientos y crear un embudo evergreen que venda todos los días.",
    painPoints: ["no_strategy", "revenue_ceiling"],
    niche: "Automatización de ventas digitales",
    expertise: "Embudos de venta, email marketing y automatización",
    targetAudience: ["women_starting", "independent_pros"],
    idealClient: "Coach o consultora que quiere vender sus programas con un embudo automático.",
    mainOfferPrice: "500_1500",
    needsToHire: ["copywriting", "web_design"],
    microphonePitch: "Busco una copywriter para mis secuencias de email y alguien que me ayude con landing pages.",
    hobbies: ["music", "social", "travel"],
    socialEnergy: "super_social",
    humanDesign: "Generadora 5/1",
    myPersonCriteria: "Alguien que le guste la tecnología tanto como los mojitos. Que sea práctica y no tenga miedo a experimentar.",
    nextObjective: "Llegar a $10k/mes con mi embudo evergreen",
    threeYearVision: "Tener mi propia plataforma SaaS de funnels para emprendedoras hispanas.",
    eventExpectation: "Clientas potenciales y alianzas con coaches que necesiten embudos.",
    purchaseReason: ["networking", "speakers", "money_talk"],
    tags: ["Funnels", "Email", "Automatización"]
  },
  {
    id: 6,
    name: "Valeria Gómez",
    specialty: "Coaching de Vida",
    image: "assets/mentor-carolina.jpg",
    bio: "Coach certificada. Te guía para desbloquear tus creencias limitantes y liderar desde tu mejor versión.",
    location: "Lima, Perú",
    instagram: "@valeriagomez.coach",
    businessStage: "selling_irregular",
    monthlyRevenue: "1000_3000",
    businessYears: "1_3",
    deliveryModel: ["service_1on1", "content_creation"],
    teamSize: "solo",
    challenge90Days: "Necesito definir un precio justo para mis sesiones y dejar de dar tanto gratis.",
    painPoints: ["impostor", "no_visibility"],
    niche: "Desarrollo personal para mujeres emprendedoras",
    expertise: "Coaching de vida, PNL y gestión emocional",
    targetAudience: ["women_starting", "general_public"],
    idealClient: "Mujer de 28-40 que siente que su potencial es mayor a sus resultados actuales.",
    mainOfferPrice: "100_500",
    needsToHire: ["social_media", "branding"],
    microphonePitch: "Busco una community manager que entienda desarrollo personal y una diseñadora para mi identidad visual.",
    hobbies: ["meditation", "read", "art", "nature"],
    socialEnergy: "one_on_one",
    humanDesign: "Reflectora 6/2",
    myPersonCriteria: "Alguien genuina que no se tome todo tan en serio. Que tenga profundidad pero también ligereza.",
    nextObjective: "Lanzar mi primer programa grupal de 8 semanas",
    threeYearVision: "Ser referente en coaching para emprendedoras en Latinoamérica con mi propia metodología.",
    eventExpectation: "Conexiones profundas y claridad sobre mi siguiente paso.",
    purchaseReason: ["community", "speakers"],
    tags: ["Coaching", "PNL", "Mindset"]
  },
  {
    id: 7,
    name: "Mariana Silva",
    specialty: "E-commerce",
    image: "assets/mentor-isabella.jpg",
    bio: "Especialista en tiendas en línea. Te ayuda a optimizar conversiones y organizar la cadena de suministro internacional.",
    location: "Santiago, Chile",
    instagram: "@marianasilva.ecom",
    businessStage: "stable_income",
    monthlyRevenue: "6000_15000",
    businessYears: "3_5",
    deliveryModel: ["physical_product", "digital_product"],
    teamSize: "small_2_4",
    challenge90Days: "Quiero expandir mi tienda a Amazon USA y necesito optimizar mi logística internacional.",
    painPoints: ["cant_delegate", "no_connections"],
    niche: "E-commerce y productos de belleza natural",
    expertise: "Tiendas online, Shopify, Amazon FBA y logística",
    targetAudience: ["women_starting", "established_brands"],
    idealClient: "Emprendedora con producto físico que quiere vender online y escalar internacionalmente.",
    mainOfferPrice: "500_1500",
    needsToHire: ["photography", "ads", "accounting"],
    microphonePitch: "Busco una fotógrafa de producto, una experta en Amazon Ads y una contadora para comercio internacional.",
    hobbies: ["exercise", "cook", "travel"],
    socialEnergy: "small_groups",
    humanDesign: "Generadora 1/3",
    myPersonCriteria: "Alguien que también tenga un negocio de producto físico y entienda los retos de inventario y logística.",
    nextObjective: "Alcanzar $20k/mes en ventas combinadas (Shopify + Amazon)",
    threeYearVision: "Tener mi marca en retailers físicos de USA y una línea de productos premium.",
    eventExpectation: "Conocer proveedoras, fotógrafas y aliadas de e-commerce.",
    purchaseReason: ["networking", "money_talk"],
    tags: ["E-commerce", "Amazon", "Shopify"]
  },
  {
    id: 8,
    name: "Lucía Fernández",
    specialty: "Diseño UX/UI",
    image: "assets/mentor-sofia.jpg",
    bio: "Product Designer. Enseña a crear productos digitales enfocados en la experiencia del usuario y la retención.",
    location: "Madrid, España",
    instagram: "@luciafernandez.ux",
    businessStage: "stable_income",
    monthlyRevenue: "3000_6000",
    businessYears: "3_5",
    deliveryModel: ["service_1on1", "digital_product"],
    teamSize: "freelancers",
    challenge90Days: "Quiero dejar de cobrar por hora y crear un producto digital que genere ingresos recurrentes.",
    painPoints: ["revenue_ceiling", "no_strategy"],
    niche: "Diseño de experiencias digitales",
    expertise: "UX/UI, Figma, investigación de usuarios y prototipado",
    targetAudience: ["established_brands", "companies"],
    idealClient: "Startup o marca establecida que necesita mejorar la experiencia de su app o plataforma.",
    mainOfferPrice: "1500_3000",
    needsToHire: ["coaching", "ads"],
    microphonePitch: "Busco una mentora de negocios que me ayude a empaquetar mi expertise en un curso y una experta en ads para venderlo.",
    hobbies: ["art", "music", "travel", "read"],
    socialEnergy: "observe_first",
    humanDesign: "Proyectora 5/2",
    myPersonCriteria: "Alguien creativa y analítica a la vez. Que entienda el mundo tech pero también tenga corazón.",
    nextObjective: "Lanzar mi curso de UX para emprendedoras",
    threeYearVision: "Tener mi estudio de diseño con un equipo remoto internacional y un SaaS propio.",
    eventExpectation: "Inspiración para hacer la transición de freelancer a fundadora.",
    purchaseReason: ["speakers", "community", "networking"],
    tags: ["Diseño", "UX/UI", "Producto"]
  },
  {
    id: 9,
    name: "Paula Ortiz",
    specialty: "Recursos Humanos",
    image: "assets/mentor-valentina.jpg",
    bio: "Asesora de talento humano. Ayuda a fundadoras a construir equipos de alto rendimiento y una cultura empresarial sana.",
    location: "Quito, Ecuador",
    instagram: "@paulaortiz.rrhh",
    businessStage: "stable_income",
    monthlyRevenue: "3000_6000",
    businessYears: "5_plus",
    deliveryModel: ["service_1on1", "group_programs"],
    teamSize: "small_2_4",
    challenge90Days: "Lanzar mi programa de consultoría para fundadoras que están contratando su primer equipo.",
    painPoints: ["no_visibility", "no_connections"],
    niche: "Gestión de talento para startups lideradas por mujeres",
    expertise: "Reclutamiento, cultura organizacional y liderazgo",
    targetAudience: ["women_starting", "established_brands"],
    idealClient: "Fundadora que pasa de solopreneur a tener su primer equipo de 2-5 personas.",
    mainOfferPrice: "500_1500",
    needsToHire: ["web_design", "copywriting", "social_media"],
    microphonePitch: "Busco quien me ayude con mi sitio web, copy para mis servicios y gestión de LinkedIn.",
    hobbies: ["read", "social", "exercise"],
    socialEnergy: "super_social",
    humanDesign: "Generadora Manifestante 6/2",
    myPersonCriteria: "Alguien líder natural, que valore a las personas tanto como los resultados.",
    nextObjective: "Tener 10 clientas fijas en mi programa de consultoría de RRHH",
    threeYearVision: "Liderar la plataforma #1 de reclutamiento para startups femeninas en LATAM.",
    eventExpectation: "Conocer fundadoras que necesiten estructurar sus equipos.",
    purchaseReason: ["networking", "community"],
    tags: ["RRHH", "Liderazgo", "Cultura"]
  },
  {
    id: 10,
    name: "Andrea Vargas",
    specialty: "Innovación y Design Thinking",
    image: "assets/mentor-carolina.jpg",
    bio: "Facilitadora de Design Thinking. Te ayuda a pivotar tu modelo de negocio hacia metodologías ágiles e innovadoras.",
    location: "San José, Costa Rica",
    instagram: "@andreavargas.innova",
    businessStage: "stable_income",
    monthlyRevenue: "3000_6000",
    businessYears: "3_5",
    deliveryModel: ["service_1on1", "group_programs"],
    teamSize: "freelancers",
    challenge90Days: "Necesito crear un taller en formato digital que pueda vender sin estar presente.",
    painPoints: ["cant_delegate", "no_strategy"],
    niche: "Innovación y metodologías ágiles",
    expertise: "Design Thinking, Lean Startup y facilitación de talleres",
    targetAudience: ["established_brands", "companies"],
    idealClient: "Empresa o emprendedora que necesita reinventar su modelo de negocio o lanzar un producto nuevo.",
    mainOfferPrice: "1500_3000",
    needsToHire: ["web_design", "ads"],
    microphonePitch: "Busco alguien que me ayude a digitalizar mis talleres presenciales en una plataforma online atractiva.",
    hobbies: ["nature", "art", "travel", "read"],
    socialEnergy: "small_groups",
    humanDesign: "Generadora 4/1",
    myPersonCriteria: "Alguien curiosa y experimental. Que le gusten los post-its tanto como Excel.",
    nextObjective: "Lanzar mi taller digital de Design Thinking para emprendedoras",
    threeYearVision: "Tener mi propia consultora de innovación con clientes en toda Centroamérica.",
    eventExpectation: "Ideas frescas y conexiones con mujeres tech-savvy.",
    purchaseReason: ["speakers", "networking"],
    tags: ["Innovación", "Design Thinking", "Agilidad"]
  },
  {
    id: 11,
    name: "Daniela Castro",
    specialty: "Comunicaciones y PR",
    image: "assets/mentor-isabella.jpg",
    bio: "Especialista en Relaciones Públicas. Te prepara para hablar en público, levantar capital y manejar medios de comunicación.",
    location: "Panamá City, Panamá",
    instagram: "@danielacastro.pr",
    businessStage: "scaling",
    monthlyRevenue: "6000_15000",
    businessYears: "5_plus",
    deliveryModel: ["service_1on1"],
    teamSize: "small_2_4",
    challenge90Days: "Quiero lanzar mi podcast y posicionarme como la voz #1 de PR para emprendedoras latinas.",
    painPoints: ["no_connections", "revenue_ceiling"],
    niche: "Relaciones públicas para emprendedoras",
    expertise: "PR, oratoria, media training y personal branding",
    targetAudience: ["independent_pros", "women_starting"],
    idealClient: "Emprendedora que quiere ser speaker, salir en medios y posicionar su marca personal.",
    mainOfferPrice: "1500_3000",
    needsToHire: ["photography", "social_media"],
    microphonePitch: "Busco una productora de podcast y una fotógrafa editorial para mi marca personal.",
    hobbies: ["social", "music", "travel"],
    socialEnergy: "super_social",
    humanDesign: "Manifestadora 3/5",
    myPersonCriteria: "Alguien carismática que entienda el poder de la visibilidad y no tenga miedo a brillar.",
    nextObjective: "Lanzar mi podcast 'Habla con Power' y conseguir 1000 suscriptoras en 3 meses",
    threeYearVision: "Ser la agencia de PR #1 para mujeres emprendedoras en Latinoamérica.",
    eventExpectation: "Contactos de medios y potenciales clientas que necesiten PR.",
    purchaseReason: ["visibility", "networking", "speakers"],
    tags: ["PR", "Oratoria", "Media"]
  },
  {
    id: 12,
    name: "Martina Ríos",
    specialty: "Finanzas e Inversiones",
    image: "assets/mentor-sofia.jpg",
    bio: "Ex-banquera de inversión. Asesora a startups en sus rondas de capital semilla y series A.",
    location: "Monterrey, México",
    instagram: "@martinarios.invest",
    businessStage: "scaling",
    monthlyRevenue: "15000_plus",
    businessYears: "5_plus",
    deliveryModel: ["service_1on1"],
    teamSize: "large_5_plus",
    challenge90Days: "Quiero crear un fondo de inversión para startups lideradas por mujeres latinas.",
    painPoints: ["no_connections"],
    niche: "Inversiones y levantamiento de capital",
    expertise: "Finanzas corporativas, inversión ángel y fundraising",
    targetAudience: ["established_brands", "companies"],
    idealClient: "Startup liderada por una mujer que está lista para su primera ronda de inversión.",
    mainOfferPrice: "3000_plus",
    needsToHire: ["legal", "branding"],
    microphonePitch: "Busco una abogada corporativa especializada en fondos de inversión y una agencia de branding.",
    hobbies: ["exercise", "read", "travel"],
    socialEnergy: "small_groups",
    humanDesign: "Proyectora 1/3",
    myPersonCriteria: "Alguien que piense en millones, no en miles. Que tenga ambición sana y visión a largo plazo.",
    nextObjective: "Cerrar las primeras 5 inversiones de mi fondo ángel",
    threeYearVision: "Administrar un fondo de $5M enfocado exclusivamente en startups de mujeres latinas.",
    eventExpectation: "Conocer fundadoras con startups invertibles y posibles co-inversionistas.",
    purchaseReason: ["networking", "money_talk"],
    tags: ["Inversiones", "Fundraising", "Capital"]
  },
  {
    id: 13,
    name: "Catalina Pineda",
    specialty: "Tecnología e IA",
    image: "assets/mentor-valentina.jpg",
    bio: "Ingeniera de datos. Enseña cómo usar Inteligencia Artificial para optimizar procesos dentro de tu emprendimiento.",
    location: "Bogotá, Colombia",
    instagram: "@catalinapineda.tech",
    businessStage: "stable_income",
    monthlyRevenue: "6000_15000",
    businessYears: "3_5",
    deliveryModel: ["service_1on1", "group_programs", "digital_product"],
    teamSize: "freelancers",
    challenge90Days: "Quiero lanzar un bootcamp de IA para emprendedoras no-tech y posicionarlo como el referente en español.",
    painPoints: ["no_visibility", "no_strategy"],
    niche: "IA y automatización para negocios",
    expertise: "Inteligencia Artificial, automatización y análisis de datos",
    targetAudience: ["women_starting", "independent_pros", "established_brands"],
    idealClient: "Emprendedora que quiere usar IA para optimizar su negocio pero no sabe por dónde empezar.",
    mainOfferPrice: "500_1500",
    needsToHire: ["branding", "copywriting", "social_media"],
    microphonePitch: "Busco una marca personal sólida, copy que traduzca tech a lenguaje humano, y alguien que maneje mis redes.",
    hobbies: ["music", "read", "exercise", "art"],
    socialEnergy: "observe_first",
    humanDesign: "Generadora 6/2",
    myPersonCriteria: "Alguien tech-curious que no le tenga miedo a los datos. Que sea nerd con estilo.",
    nextObjective: "Lanzar mi bootcamp 'IA para Emprendedoras' con 50 alumnas",
    threeYearVision: "Ser la referente #1 en IA aplicada a negocios para mujeres en habla hispana.",
    eventExpectation: "Encontrar emprendedoras que quieran implementar IA en sus negocios.",
    purchaseReason: ["speakers", "networking", "community"],
    tags: ["IA", "Tech", "Automatización"]
  },
  {
    id: 14,
    name: "Juliana Herrera",
    specialty: "Sostenibilidad",
    image: "assets/mentor-carolina.jpg",
    bio: "Consultora en Sostenibilidad. Ayuda a las empresas a implementar criterios ESG y medir su impacto ambiental y social.",
    location: "Cartagena, Colombia",
    instagram: "@julianaherrera.green",
    businessStage: "selling_irregular",
    monthlyRevenue: "1000_3000",
    businessYears: "1_3",
    deliveryModel: ["service_1on1", "content_creation"],
    teamSize: "solo",
    challenge90Days: "Necesito encontrar mis primeras 5 clientas fijas y dejar de depender de proyectos esporádicos.",
    painPoints: ["no_visibility", "impostor"],
    niche: "Sostenibilidad y responsabilidad social empresarial",
    expertise: "Consultoría ESG, economía circular y medición de impacto",
    targetAudience: ["established_brands", "companies"],
    idealClient: "Empresa mediana que quiere implementar prácticas sostenibles genuinas, no greenwashing.",
    mainOfferPrice: "500_1500",
    needsToHire: ["branding", "web_design", "social_media"],
    microphonePitch: "Busco quien me ayude a construir mi marca como consultora de sostenibilidad y una web que comunique mi valor.",
    hobbies: ["nature", "meditation", "cook", "travel"],
    socialEnergy: "one_on_one",
    humanDesign: "Reflectora 4/6",
    myPersonCriteria: "Alguien con consciencia ambiental que también entienda que los negocios necesitan ser rentables para ser sostenibles.",
    nextObjective: "Cerrar 5 contratos de consultoría ESG",
    threeYearVision: "Tener mi consultora B-Corp certificada con impacto medible en 50+ empresas.",
    eventExpectation: "Conocer emprendedoras conscientes que valoren la sostenibilidad como ventaja competitiva.",
    purchaseReason: ["community", "networking"],
    tags: ["Sostenibilidad", "ESG", "Impacto"]
  },
  {
    id: 15,
    name: "Emilia Fuentes",
    specialty: "Comercio Internacional",
    image: "assets/mentor-isabella.jpg",
    bio: "Experta en comercio exterior. Te guía paso a paso para abrir nuevos mercados en Latinoamérica y Europa.",
    location: "Santo Domingo, República Dominicana",
    instagram: "@emiliafuentes.trade",
    businessStage: "stable_income",
    monthlyRevenue: "6000_15000",
    businessYears: "5_plus",
    deliveryModel: ["service_1on1", "physical_product"],
    teamSize: "small_2_4",
    challenge90Days: "Quiero abrir un nuevo canal de distribución en Europa y necesito contactos de importadores.",
    painPoints: ["no_connections", "cant_delegate"],
    niche: "Comercio exterior y expansión internacional",
    expertise: "Exportación, regulaciones aduaneras y negociación internacional",
    targetAudience: ["established_brands", "companies"],
    idealClient: "Marca con producto físico que quiere exportar a nuevos mercados.",
    mainOfferPrice: "1500_3000",
    needsToHire: ["legal", "accounting"],
    microphonePitch: "Busco una abogada de comercio internacional y una contadora que entienda importaciones/exportaciones.",
    hobbies: ["travel", "cook", "social", "exercise"],
    socialEnergy: "super_social",
    humanDesign: "Generadora Manifestante 2/4",
    myPersonCriteria: "Alguien con mentalidad global, que hable varios idiomas o al menos piense más allá de su país.",
    nextObjective: "Abrir distribución en España y Portugal para 3 marcas clientes",
    threeYearVision: "Tener mi trading company conectando marcas latinas con el mercado europeo.",
    eventExpectation: "Contactos internacionales y emprendedoras con productos exportables.",
    purchaseReason: ["networking", "money_talk", "visibility"],
    tags: ["Comercio", "Exportación", "Internacional"]
  }
];
